  services:
    db:
      image: mysql:8.0.42
      container_name: mysql-db   
      environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: server_db
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      ports:
        - "3307:3306"
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      depends_on:
        - db                      # Сначала должен стартовать контейнер db
      ports:
          - "8080:80"               # phpMyAdmin будет доступен на порту 8080
      environment:
          PMA_HOST: db