  services:
    db:
      image: mysql:8.0-oracle
      container_name: mysql-db   
      environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: server_db
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      ports:
        - "3307:3306"